modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/apeeling/issues"
license = "MIT License"

[[mods]]
modId = "apeeling"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "apeeling:banana_peel"
configBackground = "neapolitan:textures/block/banana_bundle_side.png"
authors = "DavigJ"
credits = "Thanks to KingRolly for the banana peel sprite!"
displayURL = "https://github.com/davidjjung/apeeling"
displayName = "A-peel-ing"
description = '''
    A Neapolitan add-on that adds banana peel items.
    '''

[[dependencies.apeeling]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apeeling]]
modId = "forge"
mandatory = true
versionRange = "[47.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.apeeling]]
modId = "blueprint"
mandatory = true
versionRange = "[7.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.apeeling]]
modId = "neapolitan"
mandatory = true
versionRange = "[5.0.0,)"
ordering = "AFTER"
side = "BOTH"