modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/davidjjung/apeeling/issues"
license = "MIT License"

[[mixins]]
config = "apeeling.mixins.json"

[[mods]]
modId = "apeeling"
version = "${mod_version}"
logoFile = "logo.png"
itemIcon = "apeeling:banana_peel"
configBackground = "neapolitan:textures/block/banana_bundle_side.png"
authors = "DavigJ"
credits = "Thanks to KingRolly for the banana peel sprite!"
displayURL = "https://modrinth.com/project/apeeling"
displayName = "Apeeling"
description = '''
    A Neapolitan add-on that adds banana peel items.
    '''

[[dependencies.apeeling]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.apeeling]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.apeeling]]
modId = "blueprint"
type = "required"
versionRange = "[${blueprint},)"
ordering = "AFTER"
side = "BOTH"